name: Build & Publish Space Invaders App

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
            
      - name: Install Dependencies
        shell: bash
        run: |
            pip install wheel
            pip install -r requirements.txt

      - name: Build App
        shell: bash
        run: | 
            pyinstaller --onefile --noconsole game.py
            cp -r assets/ dist/assets/
            mv dist space-invaders

      - uses: actions/upload-artifact@v2
        with:
          name: space-invaders-${{ runner.os }}
          path: space-invaders-${{ runner.os }}
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: space-invaders-${{ runner.os }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
